### ISSUE TITLE
Edit button in building profile doesn't work

### ISSUE THREAD

**Issue by LisaTimmerman** [BPSTechServices/pepr-public#13]
I can't remember where we landed on this one, but the problem I'm trying to solve for is that I can't add or adjust a building name in the building profile using the "Edit" button. This is all that happens when I click on the button:

![image](https://user-images.githubusercontent.com/68078441/87710425-9ccebd00-c75a-11ea-8b2e-a311dd45ece8.png)

**Comment by derekwmiller** [comment]
interesting. it works on dev but not on www. I'll fix.
