### ISSUE TITLE
Reports matching to an inactive building

### ISSUE THREAD

**Issue by LisaTimmerman** [BPSTechServices/pepr-public#16]
I caught a handful of reports on the Error list that had matched to an inactive building ID. These include 1S1E23CD-13600-B1 and 1S1E01DA-100-B1 and 1S1E10CA-500-B1. I only caught it because it was flagged <20k s.f. 

Can you adjust the system so a report can only match to an ACTIVE building ID? Can this be done as part of the ID matching process? That way I can review and screen them. Sometimes people submit a report for a building that was previously in our system but is no longer required to report. Or, they have been issued a new Building ID and accidentally submit on the old one. In that case we would want to enter the new ID as a correction.

**Comment by LisaTimmerman** [comment]
Can this get prioritized to get fixed first?

I had a building manager that submitted a report with errors. The report was also submitted using an Inactive ID. The report successfully matched to the inactive ID and the result was:

-The current building contact for this building received a noncompliance notice even though a report had been submitted.
-We sent an error correction notice to a different contact that was still listed as the building contact for the Inactive version and is NOT the building contact for the building currently.

**Comment by derekwmiller** [comment]
yes. top of the list.

**Comment by derekwmiller** [comment]
done. only buildings with status = 'Active' pass the building ID check in the error report.

**Comment by LisaTimmerman** [comment]
Hey - I just ran into a building that's still matching on an "Inactive" ID. The one I'm looking at right now is: https://www.portlandmaps.com/bps/pepr/#/building/816473
This one got converted to a campus a few years ago when the building ID got split. Right now the report data is showing up as associated with the Inactive ID. The result is the campus is showing up as missing a report and I can't send a compliance confirmation notice for the report because it's attached to the wrong ID / email contact info. 

Is this retroactive and is there any way to break the connection with ones that already matched an Inactive ID?

**Comment by LisaTimmerman** [comment]
Here's another one: https://www.portlandmaps.com/bps/pepr/#/building/849475

**Comment by LisaTimmerman** [comment]
And another: https://www.portlandmaps.com/bps/pepr/#/building/875112
This one had a building ID that was retired and it looks like the reporter is still trying to use the old ID. If the system can log this as unmatched, I can update it using that window. 

There was one more as well that has an inactive match, but that one we don't actually need the report at all: https://www.portlandmaps.com/bps/pepr/#/building/750924

**Comment by LisaTimmerman** [comment]
And another one: https://www.portlandmaps.com/bps/pepr/#/building/858393

**Comment by LisaTimmerman** [comment]
https://www.portlandmaps.com/bps/pepr/#/building/821790

**Comment by derekwmiller** [comment]
this is interesting. it should not be happening based off the code that I'm looking at. did you run the error check after the new file was uploaded?

**Comment by derekwmiller** [comment]
Ok here's the deal. Portfolio manager reports that matched to an inactive building were being flagged as 'incorrect building id' but the rest of the error check was being run as well.

Is that not what you want? The other option -- which I just implemented and ran -- is to prevent the match. The result is that you'll have an unmatched portfolio manager report. Let me know what you'd like to do.

**Comment by LisaTimmerman** [comment]
Yes - please prevent the match. Ideally, it will get dumped into the "Building ID Errors" routine and then I can manually match it to the correct building profile. I need this to happen first, otherwise I end up with incorrect contacts and Building IDs in the mailing list.

**Comment by derekwmiller** [comment]
Cool. That’s how it is currently configured.

**Comment by derekwmiller** [comment]
resolved
