### ISSUE TITLE
Add new Active building to the system - 9035 SE Foster Road

### ISSUE THREAD

**Issue by LisaTimmerman** [BPSTechServices/pepr-public#24]
9035 SE Foster Road

**Comment by derekwmiller** [comment]
this is already in the system
https://www.portlandmaps.com/bps/pepr/#/building/1314979

**Comment by LisaTimmerman** [comment]
Thanks! Sorry I missed that one - I fixed the building ID error issue so the report is attached to it now.

**Comment by derekwmiller** [comment]
no worries!
