### ISSUE TITLE
Fix Potential Error(s) mailing list output

### ISSUE THREAD

**Issue by LisaTimmerman** [BPSTechServices/pepr-public#26]
Hey - it looks like in the Mailing Report, in the error tab, I'm getting buildings that don't have an ID match... I don't need reports that don't have a match to be screened for errors. Can this be fixed? In the meantime, can I just assume that any that don't have database information populated (site address, etc.) don't have a match and can be removed?

**Comment by derekwmiller** [comment]
yup
