### ISSUE TITLE
Double-check property use type error column sourcing 

### ISSUE THREAD

**Issue by LisaTimmerman** [BPSTechServices/pepr-public#28]
Can you double-check that the error checking process is using the Portfolio Manager calculated primary property use type column instead of the Self-Reported primary property use column?

I had a building flagged where the self-reported is wrong (residence hall), but the PM calculated was right (Office) and this got flagged as incorrect property use type

Property   Id | Property Name | Parent Property   Id | Parent Property   Name | Year Ending | Portland, OR   Building ID | Address 1

5864983 | Hansen   Building | Not   Applicable: Standalone Property | Not   Applicable: Standalone Property | 12/31/2019 | 1N2E35CB-3000-B2 | 12240   NE Glisan St

**Comment by derekwmiller** [comment]
it checks both
where [Primary_Property_Type___Self_Selected] not in (select use_type from bps_admin.pepr_valid_use_types) or [Primary_Property_Type___Portfolio_Manager_Calculated] not in (select use_type from bps_admin.pepr_valid_use_types)

it wasn't stated which to use in the logic file so I used both as was requested for the 'Other' use type check. 

I can change. Just confirm which you want it to use please.

![image](https://user-images.githubusercontent.com/2798800/89223737-2cae9c80-d58c-11ea-907a-fb71a010c49e.png)

**Comment by LisaTimmerman** [comment]
Oh I see. Yes, that made sense at the time, but now I think we can just use the PM-calculated field. Thank you for checking!

**Comment by derekwmiller** [comment]
done
