### ISSUE TITLE
Calculate compliance rate?

### ISSUE THREAD

**Issue by LisaTimmerman** [BPSTechServices/pepr-public#36]
Trying to remember where we landed on how to do this. Need a way to be able to calculate compliance rate based on total # of buildings. 

The formula for this is:

Total # of buildings which are Compliant, Possible Error(s), Exempt (one report or can cover multiple buildings in the case of a campus)  /  Total # of buildings (irrespective of campuses)

Ultimately, I just need a figure that I can insert it into our annual report.

**Comment by derekwmiller** [comment]
this is fine. I assume the # of buildings compliant / error / exempt is irrespective of campuses as well?

**Comment by derekwmiller** [comment]
Can you confirm the assumption above please? I'll proceed with the assumption but we should confirm. Thanks.

**Comment by LisaTimmerman** [comment]
For purposes of calculating the compliance rate error / exempt are rolled into compliant.

So, basically:

Compliance rate = compliant + errors + exempt (individual buildings) / noncompliant (individual buildings)
The reason it's like this is that it helps us account for all square footage and individual buildings that were originally identified.

When we publish the public facing data, it's shared according to reports submitted, so one campus report represents multiple buildings (they don't need to see multiple lines of the same data for each individual building) and we categorize according to compliant, errors, exempt and noncompliant and don't lump any of them together. Does that make sense?

**Comment by derekwmiller** [comment]
Compliance rate = compliant + errors + exempt (individual buildings) / noncompliant (individual buildings)

This doesn't make sense to me. That's going to give you a rate of over 100%. Shouldn't the denominator be 'all buildings'?

**Comment by LisaTimmerman** [comment]
Yes - you are totally right. Sorry - didn't have enough coffee yet...

**Comment by derekwmiller** [comment]
cool. That's how it is.
