### ISSUE TITLE
Resolve Building ID assignments for 100 SW Market / 1621 SW 1st Ave

### ISSUE THREAD

**Issue by LisaTimmerman** [BPSTechServices/pepr-public#37]
We have two buildings that have reported separately for several years that are located on the same parcel. These used to appear in MapWorks as two different Building IDs (I think maybe we requested a split). It looks like BDS merged them back into one building ID. It's now listed as 1S1E03CB-700-B1. 

The reporter submitted the two different buildings with separate reports, but used the same building ID for both of them, which isn't what it got reverted back to: 
Property Id | Property Name | Portland, OR Building ID | Address 1
2009556 | Park Square - Woolworth Building | 1S1E03CB-700-B2 | 1621 SW First Ave
2018743 | Park Square - 100 Market | 1S1E03CB-700-B2 | 100 SW Market St.

These seem to be two distinctly different buildings, they just share a walkway between them. Any ideas for how to best handle... should we request a split again?

End result needs to be that we can assign these reports to their respective buildings for compliance.

**Comment by derekwmiller** [comment]
sounds like they need to be split

**Comment by derekwmiller** [comment]
Did you request a split on this or did you intend for me to do that?

**Comment by LisaTimmerman** [comment]
I can email Neil and ask him to do it.

**Comment by LisaTimmerman** [comment]
Okay - Neil split them, but there's still a correction I need you to do. The two reports for these buildings were submitted using one ID - for 1S1E03CB-700-B2. So, presumably one of the reports (I don't know which one) is matched to that building and is marked compliant. The other building is currently marked NonCompliant because it doesn't have a repot with matching ID. I can't correct it through the Building ID correction window, because we don't have the initial filter that finds duplicate report submissions. Can you reconcile this on the back-end? Even the report that's matched currently may or may not be the right one. They do have the Building NAME in the report data and that should match with the building in our system. The other Building ID is 1S1E03CB-700-B3.

**Comment by derekwmiller** [comment]
@LisaTimmerman we need a PM ID | Building ID for these two records

**Comment by LisaTimmerman** [comment]
MATCH TO PEPR SHAKER PORTLAND BUILDING ID: 1S1E03CB-700-B2
2009556 | Park Square - Woolworth Building | 1S1E03CB-700-B2 | 1621 SW First Ave

MATCH TO PEPR SHAKER PORTLAND BUILDING ID: 1S1E03CB-700-B3
2018743 | Park Square - 100 Market | 1S1E03CB-700-B2 | 100 SW Market St.

**Comment by derekwmiller** [comment]
done.
