### ISSUE TITLE
Building ID correction fail question + bug

### ISSUE THREAD

**Issue by LisaTimmerman** [BPSTechServices/pepr-public#38]
I had a Building ID fail to update. Here's some info:

1)  PM ID: 10882747 should pair with Portland Building ID: 1S1E03DA-1800-B2
![image](https://user-images.githubusercontent.com/68078441/91475270-33a99180-e850-11ea-8639-80bf41a6d129.png)
I think this is because the status is listed as Permit-New Construction instead of Active... this doesn't make total sense as PortlandMaps has the Year Built as 2017 and they were able to submit a full year of data. What can we do?

2) I had another one that failed because the ID was Inactive... this worked as it should - it needed to be reassigned to a campus - yay! However, when I enter an ID that fails it creates this glitch:
![image](https://user-images.githubusercontent.com/68078441/91480890-73747700-e858-11ea-8d36-902484901989.png)
It keeps duplicating all the IDs that have failed to match after I entered an ID... it still works or the most recent one (at the bottom)...let me know if that doesn't make sense!

**Comment by derekwmiller** [comment]
@LisaTimmerman 

The first issue: there was already a record in the override table for that PM id (tied to the same building). If you run the error report, it should disappear from that list. If it doesn't, then we have issues.

The second: I can't replicate that. If it happens again, a refresh (crtl + r) should clear it up. If it continues and prevents you from doing work, open a new issue and we'll sort it out.

**Comment by LisaTimmerman** [comment]
For item #1 above, I still cannot get the report to match to the building ID. I ran the error report button as suggested and it doesn't yield any change.

**Comment by LisaTimmerman** [comment]
I still cannot get PM ID: 10882747 to match with Portland Building ID: 1S1E03DA-1800-B2 in the Building ID correction tool. This is holding me up from running the rest of the process. Can you adjust this manually and/or investigate what the problem is?
