### ISSUE TITLE
Create new campus for 223-225 Sw Ash St

### ISSUE THREAD

**Issue by LisaTimmerman** [BPSTechServices/pepr-public#39]
Combine building IDs 1N1E34CD-1700-B1 and 1N1E34CD-1700-B2 into a campus. 

Please let me know when done so I can provide the reporter with the new Campus ID and match the submitted report to the campus. 

Year built is 1890 and you can use the address above.

Thanks!

**Comment by derekwmiller** [comment]
done. Campus - 68
