### ISSUE TITLE
Can't see compliance status bar in building profile anymore

### ISSUE THREAD

**Issue by LisaTimmerman** [BPSTechServices/pepr-public#46]
The bar across the top of the profile that shows whether a building is non-compliant, compliant, etc. has disappeared and now it's just a white space. Can this be added back? It's nice to be able to see that at a glance.

Thanks!

**Comment by derekwmiller** [comment]
can you confirm this? i cannot reproduce.

**Comment by LisaTimmerman** [comment]
It was like that for a day or two - tried refreshing, opening up in different browsers, etc. but has since resolved and no longer a problem
