### ISSUE TITLE
Rematch duplicate report that did not come up on duplicate report list

### ISSUE THREAD

**Issue by LisaTimmerman** [BPSTechServices/pepr-public#47]
Found duplicate reports that did not come up on the duplicate report list because only one of the reporters provided the correct building ID. 

Can you please discard the report that's currently matched with 819 SW Oak (1N1E34CC-1500-B1) - PM ID 5790839?

Once you do that, I think I can match it with the correct report in the Building ID correction tool. The match fails right now because the other report is still attached to it.

**Comment by derekwmiller** [comment]
done
