### ISSUE TITLE
Can't approve Exemptions in "In-Process" tab

### ISSUE THREAD

**Issue by LisaTimmerman** [BPSTechServices/pepr-public#48]
I've got about 9 building in the "In-Process" tab of the Exemptions Track-It queue. I can't approve any of them because every time I click on one of them it just takes me back to the main dashboard screen instead of the building's profile. 

Note that several (but not all) of these are exemptions that I manually added. Those are the ones that are showing up in the queue as blank. 

I need some way of approving these because the exemptions need to be reflected in the building's compliance status and it needs to override any report they may have submitted. 

Thanks!

**Comment by LisaTimmerman** [comment]
![image](https://user-images.githubusercontent.com/68078441/94962862-06ce4700-04ac-11eb-9dde-d0546032196f.png)

This is what happens when I click on the building I want to approve in the queue.

**Comment by derekwmiller** [comment]
Ok. Let me take a look

**Comment by derekwmiller** [comment]
it's because the building you've assigned that exemption to is not in the system. i.e. not in PEPR
