### ISSUE TITLE
Compliance rate calculations don't match

### ISSUE THREAD

**Issue by LisaTimmerman** [BPSTechServices/pepr-public#49]
The figures that are showing up in the compliance rate calculation table don't seem to match what I'm seeing elsewhere in the system. Here's where I'm seeing discrepancies:

- Exemptions - the table shows 11. when I count them on the Track-It exemption tab I count 19 exemptions.

- Can you confirm whether the exemptions are calculated into the overall compliance rate? These buildings should technically be counted along with the compliant buildings rather than the noncompliant buildings. 

- Error Reports - the table shows 51. The spreadsheet with error buildings I get is 46 reports. Does this mean that it's reflecting buildings instead of reports?

Is it possible to add the word "reports" or "buildings" for each of the items in the list? That would help me keep track of how we are counting each of them.

I need these figures to include in the narrative for the annual report.

**Comment by derekwmiller** [comment]
are exempt buildings included in the 'buildings expected to report'? I would guess yes considering that they are counted as 'compliant' ... please confirm

**Comment by LisaTimmerman** [comment]
Yes - BETR is essentially all the buildings that are on our list for a given reporting year that meet the criteria that requires them to report. (I would say beginning of the year, but we do add/remove buildings to the list mid-year occasionally). It's essentially all the "Active" buildings in our system. A building can still be "Active" but have a temporary exemption for that year. 

Exempt buildings should show up with that status on our public datasheet and the map and not in any of the other categories. If they submitted a report at any point, we would want to discard it... sometimes we don't find out they qualify for an exemption until after they submit. For example, they get tossed on our error list because of low EUI, we contact them and then it turns out the building was vacant all year, so we tell them to submit an exemption request instead. 

Exempt buildings should be included in the compliance rate calculation in addition to Compliant and Error Reports. 

Compliance Rate = 
(Compliant Buildings + Potential Error Buildings + Exempt Buildings) / BETR

OR

(BETR - NonCompliant Buildings) / BETR ... in this case just make sure that Exempt buildings w/o a report submission aren't showing up as Noncompliant

**Comment by derekwmiller** [comment]
got it. this is done.
