### ISSUE TITLE
Exempt building showing up on error log - 827 NE Oregon

### ISSUE THREAD

**Issue by LisaTimmerman** [BPSTechServices/pepr-public#50]
Was reviewing the error log (using mailing list until this is built in to the system) and found a building that has an exemption. 

The exemption should remove any submitted report from being included on the "potential error(s)" or "compliant" list. 

Building Info
1N1E35BC-1800-B1
827 NE Oregon St.
PM ID: 1405062

This instance will need to be fixed before I can produce the published data set or data analysis sheet.

**Comment by LisaTimmerman** [comment]
Found another one:

6521 SW BEAVERTON-HILLSDALE HWY
1S113AA-01100-B1
PM ID: 5805561

**Comment by derekwmiller** [comment]
I thought exempt buildings were to be counted as compliant? Is that only for the compliance rate, but exclude them from the mailing list?

**Comment by derekwmiller** [comment]
exempt buildings / campus buildings are removed from the mailing list
