### ISSUE TITLE
Add Repair Services (Vehicle, Shoe, Locksmith, etc.)

### ISSUE THREAD

**Issue by LisaTimmerman** [BPSTechServices/pepr-public#8]
Add "Repair Services (Vehicle, Shoe, Locksmith, etc.)" to the accepted property use types in the error checking routine.

**Comment by derekwmiller** [comment]
you can do this via the application. let me know if you have questions.

**Comment by LisaTimmerman** [comment]
Thanks – I can see where to do this, but get this alert message when I try to add it. I can’t see that the value already exists in the list.

[cid:image001.jpg@01D6602C.9554F9D0]

**Comment by derekwmiller** [comment]
right. there was a missing value in the server request that has been resolved.
