### ISSUE TITLE
<20k s.f. flagged incorrectly

### ISSUE THREAD

**Issue by LisaTimmerman** [BPSTechServices/pepr-public#9]
These two buildings got flagged as having <20k s.f. in the error checking routine. That's not true however they both have decimal point values for their square footage. This is rare, but can happen if the user needs to enter a time weighted s.f. adjustment.

12105 | 1S1E10-200-B2 | 2750 S MOODY AVE | 1319779 | 6688285 | Potential Error(s)

11767 | CAMPUS-59 |   | 59 | 1309317 | Potential Error(s)

**Comment by derekwmiller** [comment]
Fixed. Modified the procedure that runs the error check to allow for decimals.
